### ISSUE TITLE
这个乱码是什么情况？

### ISSUE THREAD

**Issue by qtvbwfn** [HammCn/WeComRobotSDK#1]
调试截图
![图片](https://github.com/user-attachments/assets/b3023c5b-4251-4baf-8cb7-1b5e726b3241)
控制台输出截图
![图片](https://github.com/user-attachments/assets/87f5c357-0d4b-4ef4-a648-b8f5009ec8fc)

**Comment by HammCn** [comment]
[#2](#2)
